### ISSUE TITLE
[Fix] Update this quote

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/javascript-quote-generator#30]
- First letter capital
- Correct author's name

![Screenshot (1097)](https://user-images.githubusercontent.com/79108273/193464708-026fc960-38c5-40f0-a0ad-71a264ce754d.png)

**Comment by Ujjawal3** [comment]
Hi @Sanket1308 can i take this issue?

**Comment by Sanket1308** [comment]
@Ujjawal3 
Go ahead! Contribute well🚀
