### ISSUE TITLE
Make transition of images smooth

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/javascript-quote-generator#32]

**Comment by Aragorn-64** [comment]
Hi @Sanket1308 I would like to work on this :)  Can you explain the issue a bit? Do you want the transition of cards to be smoother?

**Comment by Sanket1308** [comment]
Yes! 
Go ahead! Contribute well🚀

**Comment by jose-jimmy** [comment]
Hi @Sanket1308 can you assign this issue to me

**Comment by yogesh-9999** [comment]
Hey @Sanket1308  assign this to me

**Comment by Sanket1308** [comment]
Go ahead @yogesh-9999 ! Contribute well🚀
