### ISSUE TITLE
Fetch quotes from API instead of hard-coding them

### ISSUE THREAD

**Issue by soustab10** [boradesanket13/javascript-quote-generator#47]
An API can be used to generate random and unique quotes every time, instead of hardcoding them.
If approved @Sanket1308 , please assign the issue to me.

**Comment by Sanket1308** [comment]
Go ahead! Currently we are showing image related to quote by using `keyword`

` {
    quote:
      '"The best way to find yourself is to lose yourself in the service of others."',
    person: 'Mahatma Gandhi',
    keyword: 'service',
  }`
  
  If we use quotes from API you have show random images or think about a solution for it too.
  
  Assigning it to you. Go ahead🚀

**Comment by soustab10** [comment]
Is it okay if I show the quotes from the API and a random image with the tag- "Motivation" from [Unsplash](https://source.unsplash.com/1600x900/?motivation)
guaranteeing high quality images.

**Comment by Sanket1308** [comment]
Go ahead! Contribute well🚀

**Comment by yogesh-9999** [comment]
Hey @Sanket1308  assign this to me

**Comment by soustab10** [comment]
@yogesh-9999 I am already working on this. Thank you.
