### ISSUE TITLE
Decrease the tweeter icon smaller

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/javascript-quote-generator#60]
- Make it look of same size as other icons
![Screenshot (1117)](https://user-images.githubusercontent.com/79108273/194756336-baf08c30-9a44-4050-bd3e-25c75b5499ec.png)

**Comment by G0V1NDK** [comment]
Assign me this issue

**Comment by rohinirai010** [comment]
Heyy I want to solve this issue , please assign me this issue.

**Comment by Sanket1308** [comment]
@G0V1NDK and @rohinirai010 , thanks for your interest!

@rohinirai010 , we're assigning issues on a first come first serve basis. Never PR before getting the particular issue assigned. It's against the good pratices of open source. If @G0V1NDK  isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue [here](https://github.com/Sanket1308?tab=repositories).

**Comment by rohinirai010** [comment]
> @G0V1NDK and @rohinirai010 , thanks for your interest!
> 
> @rohinirai010 , we're assigning issues on a first come first serve basis. Never PR before getting the particular issue assigned. It's against the good pratices of open source. If @G0V1NDK isn't able to complete the issue, we'll reassign accordingly. In the meantime, you can find another hacktoberfest issue [here](https://github.com/Sanket1308?tab=repositories).

Okay, I'll keep this in mind.

**Comment by G0V1NDK** [comment]
@Sanket1308 I did the task that you assigned. Kindly check the PR.
