### ISSUE TITLE
[Documentation] Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by boradesanket13** [boradesanket13/javascript-quote-generator#7]

**Comment by Shamik1836** [comment]
I can work on this issue,can you please assign this to me?

**Comment by Sanket1308** [comment]
Go ahead! Assigned.

**Comment by Shamik1836** [comment]
You can assign me once again @Sanket1308 if you wish since the file is ready

**Comment by Sanket1308** [comment]
Assigned!
